import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import MenuAction from "@/components/MenuAction";
import BookingAction from "@/components/BookingAction";


export const metadata: Metadata = {
  title: "Hotel Golden Hills",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >

        <MenuAction />
        <BookingAction />
        {children}
        <Footer />
      </body>
    </html>
  );
}
